services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/archi-tektur/gtss-api:app-${VERSION:-1.0.4}
    environment:
      APP_URL: "http://app:8080"
      # Application
      APP_ENV: "dev"
      APP_SECRET: "a9806d99cd5c1503d8af30c963c9411f"
      DATABASE_URL: "mysql://user:password@mariadb:3306/gtss-api"
  mariadb:
    image: 'mariadb:10.6'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "gtss-api"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
