doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: 'mariadb-10.6.0'
        charset: 'utf8mb4'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Geolocation:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Geolocation/Entity'
                prefix: 'App\Geolocation\Entity'
                alias: Geolocation
            Scheduling:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Scheduling/Entity'
                prefix: 'App\Scheduling\Entity'
                alias: Scheduling
            Administration:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Administration/Entity'
                prefix: 'App\Administration\Entity'
                alias: Administration

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
